version: 2
jobs:
  tests:
    docker:
      - image: circleci/golang:1.11.4
    resource_class: large
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: go get -u github.com/orbs-network/go-junit-report
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - run: sudo apt-get install -y nodejs
      - run: ./test.sh
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  flakiness:
    docker:
      - image: circleci/golang:1.11.4
    parallelism: 6
    resource_class: xlarge
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - run: sudo apt-get install -y nodejs
      - run: sudo npm install junit-xml-stats -g
      - run: go get -u github.com/orbs-network/go-junit-report
      - run:
          command: ./test.flakiness.sh
          no_output_timeout: 25m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  nightly:
    docker:
      - image: circleci/golang:1.11.4
    parallelism: 6
    resource_class: xlarge
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run:
          command: ./.circleci/nightly.sh
          no_output_timeout: 300m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  e2e:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      # Update docker-compose
      - run: sudo bash -c "rm -rf /usr/local/bin/docker-compose && pip install docker-compose==1.23.2"
      - run:
          command: ./docker/test/test.sh
          environment:
            CONSENSUSALGO: benchmark
      # Logs here belong to root
      - run: sudo rm -rf _logs
      - run:
          command: ./docker/test/test.sh
          environment:
            CONSENSUSALGO: leanhelix
      - run: ./.circleci/release-internal.sh
      - store_artifacts:
          path: _logs


#  notify_github_about_dashboard:
#    machine: true
#    steps:
#      - checkout
#      - run: python ./.circleci/post-dashboard-link.py

  success:
    machine: true
    steps:
      - run: echo 'Success'

  deploy_testnet:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/set-aws-credentials.sh
      - run: ./.circleci/deploy-testnet.sh

  e2e_testnet_benchmark:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: sleep 300
      - run: ./.circleci/e2e-testnet.sh 42

  e2e_testnet_leanhelix:
    docker:
    - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    steps:
    - checkout
    - run: ./git-submodule-checkout.sh
    - run: sleep 300
    - run: ./.circleci/e2e-testnet.sh 2013

  release:
    machine: true
    steps:
    - checkout
    - run: ./.circleci/release.sh

  autonomous_swap:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      - run: docker tag orbs:gamma-server orbsnetwork/gamma:experimental
      - run: cd vendor/github.com/orbs-network/orbs-ethereum-contracts/ && .circleci/main.sh

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            tags:
              only: /^v.*/
      - e2e:
          filters:
            tags:
              only: /^v.*/
      - flakiness
      - autonomous_swap
      - success:
          requires:
            - tests
            - e2e
            - autonomous_swap
      - deploy_testnet:
          requires:
            - e2e
          filters:
            branches:
              only:
                - master
      # - e2e_testnet_benchmark:
      #     requires:
      #       - deploy_testnet
      # - e2e_testnet_leanhelix:
      #     requires:
      #       - deploy_testnet
      - release:
          requires:
            - tests
            - e2e
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly


